version: '3'
services:
  backend:
    build: .
    command: tail -f /dev/null
    env_file:
      - backend.env
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - database
    links:
      - database:database
      - redis:redis
  database:
    image: postgres
    env_file:
      - backend.env
  redis:
    image: redis