version: '3'
services:
  backend:
    build: .
    command: tail -f /dev/null
    env_file:
      - postgresql.env
    volumes:
      - /media/evgeniy/485E45B65E459D96/Project/staff-planner:/app
    ports:
      - '3000:3000'
    depends_on:
      - database
    links:
      - database:database
  database:
    image: postgres
    env_file:
      - postgresql.env
