default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  user: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "StaffPlanner_development") %>

test:
  <<: *default
  database: StaffPlanner_test

production:
  <<: *default
  database: StaffPlanner_production
  username: StaffPlanner
  password: <%= ENV['STAFFPLANNER_DATABASE_PASSWORD'] %>
